sentences = [
    "The sun rises in the east",
    "Birds chirp melodiously in the morning",
    "The vast ocean stretches to the horizon",
    "Mountains stand tall against the sky",
    "In the distance, a waterfall cascades down the rocks",
    "The scent of freshly bloomed flowers fills the air",
    "Time flies when you're having fun",
    "Laughter echoes through the room",
    "Whispers of the wind rustle the leaves",
    "Raindrops glisten on the windowpane",
    "Books transport us to different worlds",
    "Music has the power to move our souls",
    "The symphony of colors paints the sunset sky",
    "Words have the ability to inspire and heal",
    "A gentle touch can convey more than words",
    "The aroma of freshly brewed coffee awakens the senses",
    "The moon shines brightly on a clear night",
    "Stars twinkle like diamonds in the dark sky",
    "The sound of waves crashing on the shore is soothing",
    "The rustling of pages invites us into a story",
]
