sentences = [
    "I was created at the dawn of creation I am temptation",
    "Irresistibly drifting in different directions and there is no altering that",
    "Je te laisserai des mots en dessous de les murs qui chantent",
    "Is it impossible for you to let something go and have it go whole",
    "Ako u sebi nosis more onda je sve sto volis tvoje more",
    "Zadnji dan na obali zauvjek nek traje",
    "Srecni ljudi dolaze u srce grada",
    "I do not need anyone now when I delete you maybe I will stop feeling so bad",
    "Trailing palm leaves behind me so you do not even know that I have been there",
    "My wallpaper and I are fighting a duel to the death and one or the other of us has to go",
    "The Enrichment Center is required to remind you that you will be baked and then there will be cake",
    "Beneath the stains of time the feelings disappear you are someone else I am still right here",
    "April is waving a gentle goodbye",
    "Into the frigid waters I slowly sink down down down",
    "And eventually they did find her in the water washed over like in the arms of a loved one that were embracing her",
    "This seems to be my life and if it were possible I would hand it to you entire",
    "Ja hocu zivot bolji zivot",
    "Sometimes the cord likes to break sometimes a light tries to bend away",
    "Razlila se toplina po grudima dusa beznadna a srce nema dna",
    "Nama je dobro ali mackama koje se suncaju na kotorskim bedemima je bolje",
]
